# Taps
tap "nikitabobko/tap"
tap "2389-research/tap"
tap "KyleNesium/tap"
tap "manaflow-ai/cmux"
brew "2389-research/tap/ccvault"


# CLI Tools
cask "iterm2"
brew "fish"
brew "tmux"
brew "neovim"
brew "bat"
brew "eza"
brew "ripgrep"
brew "fzf"
brew "jq"
brew "starship"
brew "grc"
brew "chezmoi"
brew "llm"
brew "datasette"
brew "gogcli"
brew "marcus/tap/sidecar"
brew "marcus/tap/td"

# Development
brew "python@3.12"
brew "uv"
brew "ruff"
brew "go"
brew "gopls"
brew "node"
brew "hugo"
brew "cloudflared"


# Utilities
brew "docker"
brew "docker-compose"
brew "docker-credential-helper"
brew "colima"
brew "xh"
brew "dust"
brew "yazi"
brew "qemu"
brew "foundry"
brew "gemini-cli"
brew "gh"
brew "just" 
cask "gcloud-cli"

# GUI Apps
cask "discord"
cask "spotify"
cask "whatsapp"
cask "obsidian"
cask "alfred"
cask "zotero"
cask "ghostty"
cask "firefox"
cask "transmission"
cask "hammerspoon"
cask "karabiner-elements"
cask "antigravity"
cask "docker-desktop"
cask "notion"
cask "zappy"
cask "spotify"
cask "claude-code"
cask "claude"
cask "miro"
cask "cmux"
cask "finicky"

# Fonts
cask "font-fira-code-nerd-font"
